name: Fetch latest data

on:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Fetch picture
      run: |-
        TIME=$(date -Is)
        mkdir -p images/16908
        curl -H "Referer: http://public.highwaystrafficcameras.co.uk/cctvpublicaccess/html/16908.html" -o images/16908/$TIME.jpeg -s http://public.highwaystrafficcameras.co.uk/cctvpublicaccess/images/16908.jpg?$TIME
        mkdir -p images/16993
        curl -H "Referer: http://public.highwaystrafficcameras.co.uk/cctvpublicaccess/html/16993.html" -o images/16993/$TIME.jpeg -s http://public.highwaystrafficcameras.co.uk/cctvpublicaccess/images/16993.jpg?$TIME

    - uses: jruipinto/ImageMagick-action@v1
      with:
        command: 'convert -delay 20 -loop 1 -layers optimize images/16908/*.jpeg traffic-camera-16908.gif'

    - uses: jruipinto/ImageMagick-action@v1
      with:
        command: 'convert -loop 1 -layers optimize -delay 580 images/16993/2020-12-22T09:55:05+00:00.jpeg -delay 20 images/16993/*.jpeg traffic-camera-16993.gif'

    - name: Push to GitHub
      run: |-
        remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git config user.name "Automated Publisher"
        git config user.email "actions@users.noreply.github.com"
        git remote add publisher "${remote_repo}"
        git show-ref
        git branch --verbose
        git checkout main
        git add -A
        git commit --amend --no-edit || exit 0
        git push --force publisher main
